alias d="/usr/bin/git --git-dir=$HOME/.files/ --work-tree=$HOME"
alias grep="grep --color=auto"
alias la="ls -alhN --color=auto --group-directories-first"
alias ls="ls -lhN --color=auto --group-directories-first"
alias m="mkdir -pv"
alias p="sudo pacman"
alias s="sudo systemctl"
alias t="touch"
alias src="source ~/.bashrc"
